services:
  - type: web
    name: wealthwise
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y libfreetype6-dev libpng-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wealthwise-db
          property: connectionString
      - key: EMAIL_USER
        value: wisewealth32@gmail.com
      - key: EMAIL_PASS
        value: azxa ydvg oxfe rmer
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GEMINI_API_KEY
        value: AIzaSyBaze8MZi4ZxPWWV0w1dFs50_07lyWtcOs
    disks:
      - name: reports
        mountPath: /app/Offlinereports
databases:
  - name: wealthwise-db
    databaseName: wealthwise_73ai
    user: wealthwise_73ai_user
